apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
  namespace: opa-system
data:
  policy.rego: |
    package istio.authz

    import input.attributes.request.http as http_request
    import input.attributes.source.principal as source_principal
    import input.attributes.destination.principal as dest_principal

    default allow = true

    allow = false if {
        http_request.method == "GET"
        contains(source_principal, "service-blue")
        contains(dest_principal, "service-yellow")
    }

    allow = false if {
        http_request.method == "GET"
        contains(source_principal, "service-green")
        contains(dest_principal, "service-blue")
    }