apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  namespace: opa-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
        - name: opa
          image: openpolicyagent/opa:latest
          args:
            - "run"
            - "--server"
            - "--addr=:8181"
            - "--set=plugins.grpc.addr=:9191"
            - "--set=decision_logs.console=true" 
            - "--set=plugins.envoy_ext_authz_grpc.path=istio/authz/allow"
          ports:
            - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: opa-service
  namespace: opa-system
spec:
  ports:
    - name: http
      port: 8181
      targetPort: 8181
    - name: grpc
      port: 9191
      targetPort: 9191
  selector:
    app: opa